export const statsData = [
  {
    title: "Total Users",
    icon: "users",
    value: "0",
    decision: "increment",
    percentage: "+16.2%",
    iconBg: "bg-totalUserBg",
    iconFg: "text-totalUserFg",
  },
  {
    title: "Students",
    icon: "premium",
    value: "0",
    decision: "decrement",
    percentage: "-08.08%",
    iconBg: "bg-premiumUserBg",
    iconFg: "text-premiumUserFg",
  },
  {
    title: "Advisors",
    icon: "userCheck",
    value: "0",
    decision: "increment",
    percentage: "+12.08%",
    iconBg: "bg-activeUserBg",
    iconFg: "text-activeUserFg",
  },
  {
    title: "Projects",
    icon: "projects",
    value: "0",
    decision: "increment",
    percentage: "+12.08%",
    iconBg: "bg-activeUserBg",
    iconFg: "text-activeUserFg",
  },
  {
    title: "Department Heads",
    icon: "userPlus",
    value: "0",
    decision: "increment",
    percentage: "+12.80%",
    iconBg: "bg-newUserBg",
    iconFg: "text-newUserFg",
  },
  {
    title: "Admins",
    icon: "userPlus",
    value: "0",
    decision: "increment",
    percentage: "+12.80%",
    iconBg: "bg-newUserBg",
    iconFg: "text-newUserFg",
  },
];
