export const sidebarItems = [
    { path: "/dashboard", icons: "dashboard", label: "Dashboard" },
    { path: "/dashboard/users", icons: "users", label: "Users" },
    { path: "/dashboard/department", icons: "department", label: "Departments" },
    { path: "/dashboard/students", icons: "students", label: "Students" },
    { path: "/dashboard/advisors", icons: "advisors", label: "Advisors" },
    { path: "/dashboard/department-heads", icons: "departmentHeads", label: "Department Heads" },
    { path: "/dashboard/premium-users", icons: "premiumUsers", label: "Premium Users" },
    { path: "/dashboard/organizations", icons: "oraganizations", label: "Organizations" },
    { path: "/dashboard/services", icons: "users", label: "Services" },
    { path: "/dashboard/projects", icons: "projects", label: "Projects" },
    { path: "/dashboard/notifications", icons: "notifications", label: "Notifications" },
    { path: "/dashboard/manuals", icons: "manuals", label: "Manuals" },
    { path: "/dashboard/chat-groups", icons: "messages", label: "Chat Groups" },
    { path: "/dashboard/photo-review", icons: "photoReview", label: "Photo Review" },
    { path: "/dashboard/reports-bans", icons: "reportsBans", label: "Reports & Bans" },
    { path: "/dashboard/sales-agents", icons: "salesAgents", label: "Sales Agents" },
    { path: "/dashboard/manage-admins", icons: "manageAdmins", label: "Manage Admins" },
    { path: "/dashboard/schedule", icons: "schedule", label: "Schedules" },
  ];
  